### ISSUE TITLE
[Bug]: No error returned to the client for a failed SQL

### ISSUE THREAD

**Issue by DanielZhangQD** [matrixorigin/matrixone#12084]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93): nightly-29b1473c
- Hardware parameters:
- OS type:
- Others:
```


### Actual Behavior

- Run TPCH Q1
- The SQL failed silently without returning any error to the client
```
MySQL [mo_cloud]> select * from system.statement_info where account = 'c04ee5ce_265e_4373_9b67_ad9b3054404a' and statement_id = 'ac64ed20-68c5-11ee-8f94-daf66a41cd7f';
+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+-------+---------------------+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-----------------------+--------------------------------------+-----------+----------------------------+----------------------------+--------------+--------+----------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+-----------+------------+-------------------+----------------+------------+---------+-----------------+------------+--------------+
| statement_id                         | transaction_id                       | session_id                           | account                              | user  | host                | database                 | statement                                                                                                                                                                                                                                                                                                                                                                                                                      | statement_tag | statement_fingerprint | node_uuid                            | node_type | request_at                 | response_at                | duration     | status | err_code | error                                                | exec_plan                                                                                                                          | rows_read | bytes_scan | stats             | statement_type | query_type | role_id | sql_source_type | aggr_count | result_count |
+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+-------+---------------------+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-----------------------+--------------------------------------+-----------+----------------------------+----------------------------+--------------+--------+----------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+-----------+------------+-------------------+----------------+------------+---------+-----------------+------------+--------------+
| ac64ed20-68c5-11ee-8f94-daf66a41cd7f | 1ca731f7-d670-425b-be44-5c20ec5becdf | a6401b04-68c5-11ee-8f94-daf66a41cd7f | c04ee5ce_265e_4373_9b67_ad9b3054404a | admin | 172.20.31.132:35540 | mo_sample_data_tpch_sf10 | select
    o_orderpriority,
    count(*) as order_count
from
    orders
where
    o_orderdate >= date '1997-07-01'
    and o_orderdate < date '1997-07-01' + interval '3' month
    and exists (
        select
            *
        from
            lineitem
        where
            l_orderkey = o_orderkey
            and l_commitdate < l_receiptdate
    )
group by
    o_orderpriority
order by
    o_orderpriority |               |                       | 65313938-6531-3462-3336-643464373132 | CN        | 2023-10-12 06:07:50.520502 | 2023-10-12 06:12:50.556119 | 300035617006 | Failed | 20101    | internal error: get dispatch process by uuid timeout | {"code":200,"message":"NO ExecPlan Serialize function","steps":null,"success":false,"uuid":"ac64ed20-68c5-11ee-8f94-daf66a41cd7f"} |         0 |          0 | [3,0,0,0,0,287,0] | Select         | DQL        |       2 | cloud_user_sql  |          0 |            0 |
+--------------------------------------+--------------------------------------+--------------------------------------+--------------------------------------+-------+---------------------+--------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------+-----------------------+--------------------------------------+-----------+----------------------------+----------------------------+--------------+--------+----------+------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------+-----------+------------+-------------------+----------------+------------+---------+-----------------+------------+--------------+
1 row in set (23.37 sec)
```

### Expected Behavior

An error is returned explicitly

### Steps to Reproduce

```Markdown
NA
```


### Additional information

The SQL is running at `2023-10-12 06:07:50.520502 UTC`, and the CN Pod restarted and became ready around that time.
```
MySQL [mo_cloud]> select status,request_at,response_at from system.statement_info where account = 'c04ee5ce_265e_4373_9b67_ad9b3054404a' and statement_id = 'ac64ed20-68c5-11ee-8f94-daf66a41cd7f';
+--------+----------------------------+----------------------------+
| status | request_at                 | response_at                |
+--------+----------------------------+----------------------------+
| Failed | 2023-10-12 06:07:50.520502 | 2023-10-12 06:12:50.556119 |
+--------+----------------------------+----------------------------+
```

```
    conditions:
    - lastProbeTime: null
      lastTransitionTime: "2023-10-12T06:04:58Z"
      status: "True"
      type: KruisePodReady
    - lastProbeTime: null
      lastTransitionTime: "2023-10-12T06:04:58Z"
      status: "True"
      type: InPlaceUpdateReady
    - lastProbeTime: null
      lastTransitionTime: "2023-10-12T06:07:49Z"
      message: CNStoreReady
      status: "True"
      type: matrixorigin.io/cn-store
    - lastProbeTime: null
      lastTransitionTime: "2023-10-12T06:05:00Z"
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: "2023-10-12T06:07:50Z"
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: "2023-10-12T06:07:43Z"
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: "2023-10-12T06:05:00Z"
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: containerd://7f2fb5885ba9f052ccf6532cd90b91e879152531b70a05b287f736d17e6d964a
      image: docker.io/matrixorigin/matrixone:nightly-29b1473c
      imageID: docker.io/matrixorigin/matrixone@sha256:e1f653c7528031721007e6753974239b39b6bb1501adc2b35e4281a9297bc48f
      lastState:
        terminated:
          containerID: containerd://9262061684d67288ce67a745d1a3821791bde625582ab3be91f424ba741aa2dc
          exitCode: 2
          finishedAt: "2023-10-12T06:07:14Z"
          reason: Error
          startedAt: "2023-10-12T06:06:43Z"
      name: main
      ready: true
      restartCount: 3
      started: true
      state:
        running:
          startedAt: "2023-10-12T06:07:42Z"
```
