### ISSUE TITLE
[Bug]: create database returns ExpectedDup error

### ISSUE THREAD

**Issue by volgariver6** [matrixorigin/matrixone#7665]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id: matrixorigin/matrixone:nightly-ff9e1913
- Hardware parameters:
- OS type:
- Others:
```

### Actual Behavior

create database returns an error "ExpectedDup"

<img width="425" alt="image" src="https://user-images.githubusercontent.com/18366608/212802119-929298f6-d2b6-4beb-9ff6-2cda046957cf.png">

### Expected Behavior

There should be no error.

### Steps to Reproduce

```Markdown
create a MO cluster on AWS with the following yaml, connect to the service and create database with name d1.
```

### Additional information

```yaml
apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: mo
  namespace: ${self-namespace}
spec:
  dn:
    cacheVolume:
      size: 1Gi
    config: |2

      [dn]

      [dn.Ckp]
      flush-interval = "60s"
      global-interval = "100000s"
      incremental-interval = "180s"
      min-count = 100
      scan-interval = "5s"

      [dn.Txn]

      [dn.Txn.Storage]
      backend = "TAE"
      fileservice = "S3"
      log-backend = "logservice"

      [dn.rpc]
      max-message-size = "100mb"

      [log]
      level = "info"
    replicas: 1
    resources: {}
  imageRepository: matrixorigin/matrixone
  version: nightly-ff9e1913
  nodeSelector:
    kubernetes.io/arch: arm64
  logService:
    config: |2

      [log]
      level = "info"
    initialConfig:
      dnShards: 1
      logShardReplicas: 3
      logShards: 1
    pvcRetentionPolicy: Delete
    replicas: 3
    resources: {}
    sharedStorage:
      s3:
        path: liubo/log-service
        region: us-west-2
        secretRef:
          name: aws
    storeFailureTimeout: 5m0s
    volume:
      size: 10Gi
  tp:
    cacheVolume:
      size: 1Gi
    config: |2

      [cn]

      [cn.Engine]
      type = "distributed-tae"

      [cn.rpc]
      max-message-size = "100mb"

      [log]
      level = "info"
    replicas: 2
    resources: {}
    serviceType: ClusterIP
```
