### ISSUE TITLE
[Bug]: create table failed after drop table on eks with old data and new image

### ISSUE THREAD

**Issue by aressu1985** [matrixorigin/matrixone#9966]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

```Markdown
- Version or commit-id (e.g. v0.1.0 or 8b23a93):nightly-29f1e83
- Hardware parameters:
  3*CN: 16C 64G
  1*DN: 16C 64G
  3*LOG: 4C 8G
- OS type:
- Others:
  DISK CACHE: 100G
  MEM CACHE: 12G
```

### Actual Behavior

when re-create mo cluster on eks with old data using new image(nightly-29f1e83), the mo cluseter can started succeccfully. but when load ssb 1G data, there are something wrong.

the table lineorder can be dropped successfully, but then create this table report error.

the test tools log:

Warning: 9 06:25:54 The table ssb_1g.lineorder cant not be created. Error: mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR at line 1: ExpectedDup
2023-06-09 06:25:54 [s3_lineorder_ssb_1g]
2023-06-09 06:25:54 Start to load data from file ssb_1/lineorder.tbl into table ssb_1g.lineorder,please wait.....
2023-06-09 06:25:54 load data url s3option {'bucket'='mo-load-data', 'filepath'='ssb_1/lineorder.tbl'} into table ssb_1g.lineorder fields terminated by ',' lines terminated by '
' parallel 'true';
Warning: 9 06:25:55 mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 11[46](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5218853049/jobs/9420210699#step:12:47) (HY000) at line 1: no such table ssb_1g.lineorder
2023-06-09 06:25:55 The data for table ssb_1g.lineorder has failed to be loaded.
2023-06-09 06:25:55 This test for [s3_lineorder_ssb_1g] has been executed failed, more info, please see the log

and sometimes , a new table loading data report Duplicate

Warning: 9 06:48:32 The table tpch_1g.part cant not be created. Error: mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1062 (HY000) at line 1: Duplicate entry '4015ca4[60](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5218853049/jobs/9420508845#step:12:61)1705f70[61](https://github.com/matrixorigin/mo-nightly-regression/actions/runs/5218853049/jobs/9420508845#step:12:62)72746b657900' for key '__mo_cpkey_col'
2023-06-09 06:48:32 [s3_part_tpch_1g]
2023-06-09 06:48:32 Start to load data from file tpch_1/part.tbl into table tpch_1g.part,please wait.....
2023-06-09 06:48:32 load data url s3option {'bucket'='mo-load-data', 'filepath'='tpch_1/part.tbl'} into table tpch_1g.part fields terminated by '|' lines terminated by '
' parallel 'true';
Warning: 9 06:48:32 mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1146 (HY000) at line 1: no such table tpch_1g.part
2023-06-09 06:48:32 The data for table tpch_1g.part has failed to be loaded.
2023-06-09 06:48:32 This test for [s3_part_tpch_1g] has been executed failed, more info, please see the log

the mo log is on s3, path: **s3://mo-ares/mo-benchmark/**

### Expected Behavior

The table should be created successfully.

### Steps to Reproduce

```Markdown
1. run a mo cluster on esk with 3*cn and the same config
2. load ssb data.
3. delete the old mo cluster ,and create a new mo cluster with the same mo-data dir and new image
4. load ssb data.
```

**Comment by aptend** [comment]
待验证

**Comment by aptend** [comment]
待验证

**Comment by aptend** [comment]
按如下配置启动集群，load tpch-1g, ssb-1g, tpcc，删除，重启再导入，反复执行，未复现，logservice 和 dn replay 的相关日志未见异常
```yaml
apiVersion: core.matrixorigin.io/v1alpha1
kind: MatrixOneCluster
metadata:
  name: test
  namespace: hanfeng
spec:
  logService:
    # LogService 副本数
    replicas: 3
    nodeSelector:
      kubernetes.io/arch: amd64
      # role: mo-x86
    pvcRetentionPolicy: Retain
    resources:
      requests:
        cpu: 2
        memory: 8Gi
    sharedStorage:
      s3:
        path: hanfeng/anyway
        # bucket 所在的 region
        region: us-west-2
        secretRef:
          name: aws
    volume:
      size: 10Gi
      # 使用 GP3
      storageClassName: gp3
    config: |2
      [log]
      level = "info"
      format = "console"
  dn:
    # DN 副本数
    replicas: 1
    nodeSelector:
      kubernetes.io/arch: amd64
      # role: mo-x86
    resources:
      requests:
        cpu: 2
        memory: 2Gi
    cacheVolume:
      size: 10Gi
      storageClassName: gp3
    config: |2
      [log]
      level = "info"
      format = "console"
      [dn.Txn.Storage]
      backend = "TAE"
      fileservice = "S3"
      log-backend = "logservice"
      [dn.Ckp]
      flush-interval = "60s"
      min-count = 100
      scan-interval = "5s"
      incremental-interval = "180s"
      global-interval = "100000s"
  tp:
    # CN 副本数
    replicas: 2
    nodeSelector:
      kubernetes.io/arch: amd64
      # role: mo-x86
    resources:
      requests:
        cpu: 2
        memory: 8Gi
    cacheVolume:
      size: 10Gi
      storageClassName: gp3
    config: |2
      [cn.Engine]
      type = "distributed-tae"
      [log]
      level = "info"
      format = "console"
  imageRepository: matrixorigin/matrixone
  version: nightly-6c14bc3
```
